### ISSUE TITLE
[BUG] Improper encoding for `callback`

### ISSUE THREAD

**Issue by MisterTicot** [stellarguard/stellar-uri#7]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

Found in [https://stellarguard.github.io/stellar-uri/demo/], Sample TX URI. `callback` should start by `uri:` but the column gets encoded to `%3A`.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by pselden** [comment]
Can you explain a bit more? There's a "convenience" method that strips the initial "url:" part of the callback when it is fetched (note: it's ur-EL, not ur-EYE)

What part is being encoded improperly? Doesn't the entire callback need to be url-encoded?

**Comment by MisterTicot** [comment]
I would do

```
callback => `url:${encodeURIComponent(callback)}
```

Rather than:

```
callback => encodeURIComponent(`url:${callback}`)
```

From the specs, I read that only the callback should be encoded:

> The URL-encoded callback will be prefixed with its own namespace to denote whether this is a url callback or some other form of callback.

**Comment by pselden** [comment]
: is a reserved character in the URI spec and is supposed to be encoded when used as part of a query parameter. https://tools.ietf.org/html/rfc3986#section-2.2

I’m not manually building the URI string by concatenating pieces together, I’m using the built in URL class which handles encoding and decoding by itself. I believe this is the correct implementation.

**Comment by MisterTicot** [comment]
What the linked docuent says is that `:` is a reserved character for the exact purpose of serving as a field separator in cases such as this one:

> components and subcomponents [...] are delimited by characters in the "reserved" set.

The SEP-0007 specs says that the callback should be URL-encoded *then* prefixed by `uri:`.

**Comment by pselden** [comment]
I've posted on the mailing list asking for clarification.

**Comment by pselden** [comment]
Actually in the example it shows it encoded: https://github.com/stellar/stellar-protocol/commit/d4c556634d4bf41b44e5f30abc1ecd105b445d47#diff-afc043c02ee1eef064c106f886302a9bR45

**Comment by MisterTicot** [comment]
Good catch! I'll wait for a clear answer in the list as it is a bit contradictory, now.
That's a shame that the URL build-in impose arbitrary restrictions on top of the standard, though.

**Comment by nikhilsaraf** [comment]
There are very clear arguments for both sides, although my original intention was for the `:` to be encoded as well, like in the example, primarily to keep the values of query params standardized as either all URL-encoded or not to avoid special handling of specific fields as much as possible.

The line `If the value is present then it should be interpreted as a URL-encoded callback` was intended to convey this aspect, but on reading it a few times I can see the ambiguity caused by specifying `url:` as an example, which has also been updated.

The expected usage when creating the callback is like Paul's example code in the `SEP7 Clarifications` stellar-dev discussion email thread.

Thank you @MisterTicot and @pselden for bringing this up. I've [updated the SEP](https://github.com/stellar/stellar-protocol/commit/7744035270581f70056b1d12ff257718c8c2d4e0) to resolve this ambiguity.

**Comment by MisterTicot** [comment]
Thank you guys, I updated my code accordingly (to be released next saturday).
